name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: lgcxc
          base: main
          head: main
          
      - name: Check for Failure
        if: failure()
        run: |
            echo "No commits"
            exit 0
